<div class="page-title">
    <h1>FAQ</h1>
</div>

<?php
    echo $this->getPagerHtml();
    if (!$this->isDisabledAsk()):?>
    <h2><a href="<?php echo $this->getQuestionAskUrl() ?>">Ask a question</a></h2>
<?php endif ?>

<h2>Answers</h2>

<?php foreach ($this->getCollection() as $item): ?>
    <table class="data-table">
        <tr><th>Name</th><td><?php echo $item->getName(); ?></td></tr>
        <tr><th>Email</th><td><?php echo $item->getEmail(); ?></td></tr>
        <tr><th>Question</th><td><?php echo $item->getQuestionText(); ?></td></tr>
        <tr><th>Answer</th><td><?php echo $item->getAnswerText(); ?></td></tr>
        <tr><th>Date</th><td><?php echo $item->getCreatedAt(); ?></td></tr>
    </table><br>
<?php endforeach; ?>

<?php echo $this->getPagerHtml(); ?>
